#!/usr/bin/env python3
"""
texbundle - zip only the files actually needed to build a LaTeX PDF.

Builds the document once with -recorder, which makes LaTeX write a .fls file
listing every path it opened. Everything under the project root gets bundled;
TeX distribution files and build artifacts do not.

Usage:
    texbundle                          # main.tex -> bundle.zip
    texbundle paper.tex -o submit.zip
    texbundle thesis.tex -e xelatex --include-pdf
    texbundle main.tex --skip-build --dry-run

Requires only the standard library. Python 3.9+.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import zipfile
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path


def _version() -> str:
    try:
        return version("texbundle")
    except PackageNotFoundError:  # pragma: no cover - not installed
        return "0.0.0"


# Regenerated by whoever rebuilds the project, so they are left out.
# .bbl is deliberately absent from this list: arXiv and many journals do not
# run BibTeX, so the compiled bibliography has to travel with the sources.
SKIP_SUFFIXES = (
    ".aux", ".log", ".out", ".toc", ".lof", ".lot", ".fls", ".fdb_latexmk",
    ".nav", ".snm", ".vrb", ".blg", ".idx", ".ilg", ".ind", ".glo", ".gls",
    ".glg", ".acn", ".acr", ".alg", ".bcf", ".run.xml", ".synctex.gz",
    ".synctex", ".dvi", ".xdv", ".upa", ".upb",
)


def build(main: Path, engine: str) -> None:
    """Compile once with -recorder so LaTeX emits the .fls dependency log."""
    job = main.stem

    if shutil.which("latexmk"):
        mode = {"xelatex": "-xelatex", "lualatex": "-lualatex"}.get(engine, "-pdf")
        cmd = ["latexmk", mode, "-interaction=nonstopmode",
               "-latexoption=-recorder", str(main)]
        print(f"Building with latexmk ({engine})...", flush=True)
        rc = subprocess.call(cmd)
    else:
        if not shutil.which(engine):
            sys.exit(f"error: neither latexmk nor {engine} found on PATH")
        print(f"latexmk not found; running {engine} directly...", flush=True)
        run = [engine, "-recorder", "-interaction=nonstopmode", str(main)]
        rc = subprocess.call(run)
        if shutil.which("bibtex"):
            subprocess.call(["bibtex", job],
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.call(run)
        rc = subprocess.call(run)

    if rc != 0:
        print(f"warning: build exited {rc}; check {job}.log before trusting "
              f"the file list", file=sys.stderr)


def parse_fls(fls: Path, root: Path) -> list[Path]:
    """Return project-local files listed as INPUT in the .fls, deduplicated."""
    base = root
    inputs: list[str] = []

    # latin-1 never raises on odd bytes; .fls is ASCII paths in practice.
    with fls.open(encoding="latin-1") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("PWD "):
                base = Path(line[4:].strip())
            elif line.startswith("INPUT "):
                inputs.append(line[6:].strip())

    root_key = os.path.normcase(str(root))
    seen: dict[str, Path] = {}

    for raw in inputs:
        # Path() copes with '\' and '/' on Windows; on POSIX a stray '\'
        # would be a literal character, but .fls written by a POSIX TeX
        # uses '/' anyway.
        p = Path(raw)
        if not p.is_absolute():
            p = base / p

        try:
            p = p.resolve(strict=False)
        except OSError:
            continue

        if not p.is_file():
            continue

        # Case-insensitive containment test, needed on Windows and macOS.
        key = os.path.normcase(str(p))
        if not key.startswith(root_key + os.sep):
            continue

        name = p.name.lower()
        if any(name.endswith(s) for s in SKIP_SUFFIXES):
            continue

        seen.setdefault(key, p)

    return sorted(seen.values(), key=lambda q: str(q).lower())


def write_zip(files: list[Path], root: Path, out: Path) -> None:
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in files:
            # as_posix() keeps the archive readable on every platform.
            arc = f.relative_to(root).as_posix()
            print(f"  {arc}")
            zf.write(f, arc)


def main() -> int:
    ap = argparse.ArgumentParser(
        prog="texbundle",
        description="Zip only the files needed to build a LaTeX PDF.")
    ap.add_argument("--version", action="version",
                    version=f"%(prog)s {_version()}")
    ap.add_argument("main", nargs="?", default="main.tex",
                    help="main .tex file (default: main.tex)")
    ap.add_argument("-o", "--out", default="bundle.zip",
                    help="output archive (default: bundle.zip)")
    ap.add_argument("-e", "--engine", default="pdflatex",
                    choices=["pdflatex", "xelatex", "lualatex"])
    ap.add_argument("--include-pdf", action="store_true",
                    help="also add the compiled PDF")
    ap.add_argument("--skip-build", action="store_true",
                    help="reuse an existing .fls instead of recompiling")
    ap.add_argument("--dry-run", action="store_true",
                    help="list the files but write no archive")
    args = ap.parse_args()

    main_tex = Path(args.main)
    if not main_tex.is_file():
        return f"error: no such file: {main_tex} (run from your project root)"

    root = Path.cwd().resolve()
    job = main_tex.stem
    fls = root / f"{job}.fls"

    if not args.skip_build:
        build(main_tex, args.engine)

    if not fls.is_file():
        return (f"error: {fls.name} was not created. Confirm the build ran and "
                f"that your engine supports -recorder.")

    files = parse_fls(fls, root)

    if args.include_pdf:
        pdf = root / f"{job}.pdf"
        if pdf.is_file():
            files.append(pdf)

    if not files:
        return f"error: no project files found in {fls.name} - nothing to bundle."

    print("\n--- bundling ---")

    if args.dry_run:
        for f in files:
            print(f"  {f.relative_to(root).as_posix()}")
        print(f"\n(dry run: {len(files)} files, no archive written)")
        return 0

    out = (root / args.out).resolve()
    write_zip(files, root, out)

    kb = out.stat().st_size / 1024
    print(f"\nWrote {out.name}  ({len(files)} files, {kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())